# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
# Site settings
title: Shinwon's Page!
description: 'Business Card Page'
url: 'http://LeeShinwon.github.io'
baseurl: ''
profilepic: 'https://news.imaeil.com/inc/photos/2020/07/21/2020072114264938857_l.jpg'
bkimage: 'https://news.imaeil.com/inc/photos/2020/07/21/2020072114264938857_l.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Thomas Zühlke'
  email: info@thomas-zuehlke.de
  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  tzuehlke
  linkedin_username:  thomas-zühlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
